=== Stic51/Cours/RT0704 - prog appli réseau/projet/serveurQcm/listQCM/qcmSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="qcm">
        <xs:complexType>
            <xs:element name="question" type="xs:string" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="intitule" type="xs:string"/>
                        <xs:element name="rep" type="xs:string" minOccurs="2" maxOccurs="4"/>
                        <xs:complexType>
                            <xs:attribute name="num" type="xs:integer" use="required"/>
                        </xs:complexType>
                    </xs:sequence>
                    <xs:attribute name="num" type="xs:integer" use="required"/>
                </xs:complexType>   
            </xs:element>
            <xs:attribute name="idQcm" type="xs:integer" use="required"/>
            <xs:attribute name="formation" type="xs:string" use="required"/>
            <xs:attribute name="matiere" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Stic51/Cours/RT0704 - prog appli réseau/projet/serveurQcm/listQCM/RT704.xml
<?xml version="1.0" encoding="UTF-8"?>
<qcm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="qcmSchema.xsd" idQcm="1" formation="RTA" matiere="RT0704">
    <question num="1">
        <intitule>Cette matière est-elle bien?</intitule>
        <rep numRep="1">Oui</rep>
        <rep numRep="2">Oui</rep>
    </question>
    <question num="2">
        <intitule>Recommendez-vous cette matière?</intitule>
        <rep numRep="1">Oui</rep>
        <rep numRep="2">Non</rep>
        <rep numRep="3">Peut-être</rep>
        <rep numRep="4">D la réponse D</rep>
    </question>
</qcm>
